#+TITLE: Package.el & use-package Setup
#+AUTHOR: Stig Brautaset
#+OPTIONS: f:t
#+PROPERTY: header-args:sh         :tangle yes
#+PROPERTY: header-args            :results silent
* Add Package Archives

  I install quite a few packages from [[http://melpa.org/][melpa]]. Before we can install packages,
  we need to add the URLs of the package archives we want to use.

  I use the Melpa package repos. Marmelade seems to largely overlap with
  melpa, so let's ignore that.

  #+BEGIN_SRC emacs-lisp
    (add-to-list 'package-archives '("melpa" . "http://melpa.milkbox.net/packages/"))
  #+END_SRC

  I want to install the `org-plus-contrib' package, mostly for the `org-mime'
  package, so need to use the org Melpa repo.

  #+BEGIN_SRC emacs-lisp
    (add-to-list 'package-archives '("org" . "http://orgmode.org/elpa/") t)
  #+END_SRC

* Install =use-package=

  I use the excellent [[https://github.com/jwiegley/use-package][use-package]] for installing & configuring packages.
  Because it is /itself/ installed via Melpa, there's a minor bootstrapping
  problem: we have to make sure it is installed before we can use it to
  install the rest of the packages.
  
  #+BEGIN_SRC emacs-lisp
    (unless (package-installed-p 'use-package)
      (message "%s" "Refreshing package database...")
      (package-refresh-contents)
      (package-install 'use-package))
  #+END_SRC

  Configure =use-package= to pre-compile the configuration for faster loading.

  #+BEGIN_SRC emacs-lisp
    (eval-when-compile
      (require 'use-package))
    (require 'bind-key)
  #+END_SRC

  Now we can use =use-package= to install the rest of the packages we want.
